"""'User增加新的字段'

Revision ID: 9fe72647e29c
Revises: 0d2d73dab2c8
Create Date: 2022-03-01 21:13:41.534709

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9fe72647e29c'
down_revision = '0d2d73dab2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(),
                                    nullable=True))  # ### end Alembic
    # commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')  # ### end Alembic commands ###
